export const WEB3_RECEIVE_ACCOUNT = 'web3/RECEIVE_ACCOUNT';
export const WEB3_CHANGE_ACCOUNT = 'web3/CHANGE_ACCOUNT';

export const SEARCH_DOMAIN_SUCCESS = 'SEARCH_DOMAIN_SUCCESS';
export const ADD_DOMAIN_TO_CART = 'ADD_DOMAIN_TO_CART';