export const WEB3_RECEIVE_ACCOUNT = 'web3/RECEIVE_ACCOUNT';
export const WEB3_CHANGE_ACCOUNT = 'web3/CHANGE_ACCOUNT';

export const SEARCH_DOMAIN_SUCCESS = 'SEARCH_DOMAIN_SUCCESS';
export const SEARCH_DOMAIN_CLEAR = 'SEARCH_DOMAIN_CLEAR';

export const ADD_DOMAIN_TO_CART = 'ADD_DOMAIN_TO_CART';
export const REMOVE_DOMAIN_FROM_CART = 'REMOVE_DOMAIN_FROM_CART';
export const ADD_IP_TO_DOMAIN = 'ADD_IP_TO_DOMAIN';
export const BUY_DOMAIN_SUCCESS = 'BUY_DOMAIN_SUCCESS';